### ISSUE TITLE
php artisan make:module not working

### ISSUE THREAD

**Issue by kyonkopa** [Artem-Schander/L5Modular#35] opened 2017-06-17 09:57 UTC
This command returns make:module not defined

**Comment by Artem-Schander** [comment] 2017-06-17 14:54
Is the Serviceprovider in the corresponding config array?

**Comment by kyonkopa** [comment] 2017-06-17 17:22
Yes it is, but it still didn't work so this is what i did to fix it.
`    protected $commands = [
        \ArtemSchander\L5Modular\Console\ModuleMakeCommand::class
    ];`
in Console\Kernel.php
After this it worked

**Comment by Artem-Schander** [comment] 2017-06-19 06:09
Which laravel version do you have this issue on?
Would you also post the content of your `config/app.php`

**Comment by kyonkopa** [comment] 2017-06-20 03:00
Laravel version 5.4
app.php
```
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        \ArtemSchander\L5Modular\ModuleServiceProvider::class
```

**Comment by Artem-Schander** [comment] 2017-06-20 06:58
I cant reproduce this issue.
There must be something with your laravel installation.
Everything runs fine after I've done these steps:
1. `laravel new l5-modular`
2. `cd l5-modular`
3. `composer require artem-schander/l5-modular`
4. add the `ArtemSchander\L5Modular\ModuleServiceProvider::class,`to the providers array 
in `config/app.php`
5. `php artisan` returns the following (among others)
```
make
  make:auth            Scaffold basic login and registration views and routes
  make:command         Create a new Artisan command
  make:controller      Create a new controller class
  make:event           Create a new event class
  make:job             Create a new job class
  make:listener        Create a new event listener class
  make:mail            Create a new email class
  make:middleware      Create a new middleware class
  make:migration       Create a new migration file
  make:model           Create a new Eloquent model class
  make:module          Create a new module (folder structure)
  make:notification    Create a new notification class
  make:policy          Create a new policy class
  make:provider        Create a new service provider class
  make:request         Create a new form request class
  make:seeder          Create a new seeder class
  make:test            Create a new test class
```

Closing issue for now. Anyhow, feel free to post updates.

**Closed by Artem-Schander** 2017-06-20 06:58 UTC

**Comment by fxbytes-jaiprakash** [comment] 2018-09-28 09:12
Hi,
I'm using laravel 5.7
I'm getting below error while i run "php artisan make:module name" command
Command "make:module" is not defined. 

Thanks in advance

**Comment by Artem-Schander** [comment] 2018-09-28 20:20
@fxbytes-jaiprakash 
I have no issues with the latest version (5.7.6)
Please follow the instructions in my comment from 20 Jun 2017 (or the readme)

**Comment by Danilo162** [comment] 2019-12-04 12:06
hi I use laravel 6.2, this is my first time I use L5 modular, I can not use the session (auth () -> user ()) in the controllers and views of my module, thank you.

**Comment by Danilo162** [comment] 2019-12-04 12:12
hi I use laravel 6.2, this is my first time I use L5 modular, I can not use the session (auth () -> user ()) in the controllers and views of my module, thank you.

**Comment by Artem-Schander** [comment] 2019-12-04 14:02
@Danilo162 
There are no known issues with the auth middleware. Please check the [laravel docs](https://laravel.com/docs/5.8/authentication#protecting-routes).
And it would be nice if you could open a new issue, If the issue persist.
